Numpy.random is a tool used in python to generate a random selection of numbers or random datasets. There are various differentiations of numpy.random which generate a vast variety of random numbers. Numpy is generally imported as np (an abreviation of numpy), which is an advantage saving us the time to type numpy each time we use it. Please see below.

In [4]:
import numpy as np

Numpy.random (np.random) does not work on it's own and returns an error. It has to be used along with a function.

In [5]:
np.random(7)

TypeError: 'module' object is not callable

Numpy.random.rand generates a random set of numbers between 0 and 1 but not including 1. In the example below 7 random numbers between 0 and 1 but not including 1 are generated.

In [3]:
np.random.rand(7)

array([ 0.77374098,  0.88300658,  0.35530373,  0.37633212,  0.69435879,
        0.05658372,  0.97429311])

Below 20 random numbers between 0 and 1 not including 1 are produced. When using np.random.rand(x), X is equivalent to the amount of random numbers generated.

In [4]:
np.random.rand(20)

array([ 0.37917758,  0.28448135,  0.47878006,  0.00293097,  0.6312022 ,
        0.82709011,  0.10570382,  0.58499114,  0.3115457 ,  0.29705997,
        0.0297122 ,  0.6244791 ,  0.70020955,  0.34630853,  0.07069719,
        0.0622925 ,  0.80863467,  0.53400819,  0.02526513,  0.43174013])

Np.random.rand(a,b) generates a random selection of numbers between 0 and 1 not including 1, however (a) represents the number of rows and (b) represents the amount of random numbers in that row. Please see below where 3 rows with 4 numbers in each row are generated.

In [6]:
np.random.rand(3, 4)

array([[ 0.94634915,  0.05739633,  0.7632177 ,  0.77783606],
       [ 0.31012589,  0.36351215,  0.35428922,  0.11070302],
       [ 0.42042899,  0.60693288,  0.3635991 ,  0.37560407]])

In [2]:
np.random.normal(5)

NameError: name 'np' is not defined

Numpy.random is a tool used in python to generate a random selection of numbers or random datasets. There are various differentiations of numpy.random.

Numpy.random.rand generates a random set of numbers between 0 and 1 but not including 1.Numpy.random is a tool used in python to generate a random selection of numbers or random datasets. Please see example below:


In [ ]:
numpy.random.rand(2)

In [ ]:
np.random.normal(55)

In [7]:
np.random.normal

<function RandomState.normal>

In [7]:
np.random.normal[2,5]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
np.random.rand(6)

In [ ]:
np.random.rand(4)