# Numpy.Random Package in Python
Numpy.random is a tool used in python to generate a random selection of numbers or random datasets. There are various differentiations of numpy.random which generate a vast variety of random numbers.These random number generators are suitable for generating numbers for spacial and graphical distributions.The package must first be imported in order to access it. Numpy is generally imported as np (an abreviation of numpy), which is an advantage saving us the time to type numpy each time we use it. Please see below.

In [11]:
#importing numpy as np
import numpy as np

Numpy.random (np.random) does not work on it's own and returns an error. It has to be used along with a function.

In [12]:
np.random(7)

TypeError: 'module' object is not callable

# Simple Random Data
Simple Random Data is a colllection of functions within the numpy.random package that generates various random outcomes of data or subsets that have an equal probability of being chosen (https://www.investopedia.com/terms/s/simple-random-sample.asp). The are 10 functions that can be used in conjunction with numpy.random in order to generate simple random data. These will be discussed in more detail below.

Numpy.random.rand(x) generates a random set of numbers between 0 and 1 but not including 1. In the example below 7 random numbers between 0 and 1 but not including 1 are generated. X represents the number of random numbers that will be generated by the function. As see below np.random.rand does not generate any data and a value must be inserted for the value of 'x' in order to generate a random number.

In [ ]:
np.random.rand

In [ ]:
np.random.rand(7)

Below 20 random numbers between 0 and 1 not including 1 are produced. When using np.random.rand(x), X is equivalent to the amount of random numbers generated.

In [ ]:
np.random.rand(20)

Np.random.rand(a,b) generates a random selection of numbers between 0 and 1 not including 1, however (a) represents the number of rows and (b) represents the amount of random numbers in that row. Please see below where 3 rows with 4 numbers in each row are generated.

In [ ]:
np.random.rand(3, 4)

In [ ]:
np.random.randn(29)

Numpy.random is a tool used in python to generate a random selection of numbers or random datasets. There are various differentiations of numpy.random.

Numpy.random.rand generates a random set of numbers between 0 and 1 but not including 1.Numpy.random is a tool used in python to generate a random selection of numbers or random datasets. Please see example below:


In [ ]:
#np.rand.rand(x) generates an array of x amount of numbers between 0 and 1 but not including 1. nupy
#In the examples below an array of 6 and 25 random numbers are created.
np.random.rand(6)


In [ ]:
np.random.rand(25)

In [ ]:
np.random.choice(522)

In [ ]:
np.random.random(2)

In [ ]:
np.random.randn(1)

In [ ]:
np.random.randn(45)

Np.random.bytes(x) returns random bytes. The higher the value of x the longer the random bytes printed out. Please see exmples below where x is 3 and a small random byte is printed, while when x is 56 a much longer output is produced.

In [ ]:
np.random.bytes(3)

In [ ]:
np.random.bytes(12)

In [ ]:
np.random.bytes

In [ ]:
np.random.bytes(56)

Permutations are defined as the list of all possible ways a number of things could be re-arranged eg. a list of numbers or datasets.

In [ ]:
#np.random.permutation(x) will randomly re-arrange all the numbers from zero up to 'x' but not including 'x'. 
#In the example below all the numbers listed from zero to 15 but not including 15 are randomly listed in no particular order.
np.random.permutation(15)

In [ ]:
#Below a list of numbers is provided and once the code is ran,those numbers in the list are returned in no particular order. 
#Each time this is ran the numbers in the list are randomly re-arranged.
np.random.permutation([7,12,5,24,32,50])

In [ ]:
#arr = np.arrange(x).reshape((a, b))
#The below function consists of of 2 rows of 6 numbers between 0 to 12 but not including 12 randomly re-arranged in no particular
#order. 'x' represents the numbers prior to that the selected number, while 'a' represents the number of rows and 'b' represents
#how many numbers will be in each row.

arr = np.arange(12).reshape((2, 6))
np.random.permutation(arr)

In [ ]:
#It is important to note this function does not work when the value of 'a' or 'b' does not divide evenly into 'x'.
arr = np.arange(16).reshape((3, 5))
np.random.permutation(arr)

In [13]:
#It is important to note this function does not work when the value of 'a' or 'b' does not divide evenly into 'x'.
# However in the case of where x is 16 the values of a and b can be made up of '2 & 8' or '4 & 4' or '16 & 1'. 
#The value given to a or b can completely change the results eg. if a is 1 and b is 16 then one row with sixteen numbers between
# 0 and 16 but not including 16 is created.
arr = np.arange(16).reshape((1, 16))
np.random.permutation(arr)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [14]:
#Whereas when a is 16 and b is 1, 16 rows with one number in each are generated.
arr = np.arange(16).reshape((16, 1))
np.random.permutation(arr)

array([[ 4],
       [ 8],
       [ 1],
       [ 6],
       [ 0],
       [11],
       [15],
       [ 5],
       [ 7],
       [ 9],
       [14],
       [ 2],
       [10],
       [12],
       [13],
       [ 3]])

In [15]:
arr = np.arange(16).reshape((8,2 ))
np.random.permutation(arr)

array([[ 6,  7],
       [12, 13],
       [14, 15],
       [ 4,  5],
       [10, 11],
       [ 0,  1],
       [ 8,  9],
       [ 2,  3]])

# Distributions:
Below various examples of disbrution fucntions within in the numpy.random package in python will be discussed.

In [16]:
#np.random.uniform(x) generates a random number up to the value of x but not including x.
#https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.uniform.html#numpy.random.uniform
np.random.uniform(2)

1.6574571025104734

In [17]:
#np.random.uniform(a,b) generates a random between a and b but not including b.
np.random.uniform(4,6)

5.782452015927482

In [18]:
np.random.uniform(1)
#no matter how many times the above code was ran it only ever generated the number 1.

1.0

In [19]:
# np.random.uniform(a, b, c) generates a list of random numbers between the value of a and b but not including b. C determines 
#the amount of random numbers generated in the list.
np.random.uniform(2, 4, 6)

array([ 3.53393826,  2.94598017,  2.89006335,  2.71315673,  2.79814995,
        3.60029042])

In [20]:
#below 100 random numbers are generated between the values of -1 and 0 but not including 0.
np.random.uniform(-1,0,100)

array([-0.0013196 , -0.77330388, -0.03118767, -0.21339168, -0.63067455,
       -0.22106232, -0.06144439, -0.73185315, -0.13752976, -0.83761048,
       -0.98130847, -0.92943441, -0.86775219, -0.08004693, -0.20833023,
       -0.75870862, -0.6138866 , -0.43885185, -0.67907554, -0.19207096,
       -0.99074533, -0.59107094, -0.4558249 , -0.33862978, -0.68430862,
       -0.75783891, -0.16355163, -0.16143044, -0.39794958, -0.06765075,
       -0.31126878, -0.09873849, -0.56669654, -0.35369006, -0.79974773,
       -0.01957544, -0.0216154 , -0.02537597, -0.71774987, -0.31881934,
       -0.51475037, -0.44137186, -0.32473444, -0.6619348 , -0.91626881,
       -0.5756637 , -0.01235534, -0.73611074, -0.25493128, -0.50632812,
       -0.51050851, -0.06684642, -0.45968493, -0.9141453 , -0.45662301,
       -0.6979567 , -0.65631625, -0.20651006, -0.07825124, -0.45471703,
       -0.46952539, -0.20399378, -0.07991036, -0.52531648, -0.97363395,
       -0.50399736, -0.61348722, -0.20240729, -0.53467749, -0.01

In [21]:
# the distribution function below requires at least 3 numbers for it to work. It then generates a random number between the lowest
#number and the highest number however, not including the highest number.
np.random.triangular(2, 3,5)

3.991733429913081

In [22]:
#below 6 random numbers are generated between the values of -2 up to 100 but not including 100.
np.random.triangular(-2, 20, 100, 6)

array([ 54.62751903,  20.94583525,  21.32102948,  41.46154975,
         9.94491108,   8.5588817 ])

In [23]:
#The triangular distribtion can only take a max of 4 positional arguments
np.random.triangular(-20, 4, 98, 5, 8)

TypeError: triangular() takes at most 4 positional arguments (5 given)

In [27]:
np.random.rand(4)

array([ 0.67493765,  0.25717196,  0.29377077,  0.81811746])