Numpy.random is a tool used in python to generate a random selection of numbers or random datasets. There are various differentiations of numpy.random which generate a vast variety of random numbers.These random number generators are suitable for generating numbers for spacial and graphical distributions.The package must first be imported in order to access it. Numpy is generally imported as np (an abreviation of numpy), which is an advantage saving us the time to type numpy each time we use it. Please see below.

In [2]:
#importing numpy as np
import numpy as np

Numpy.random (np.random) does not work on it's own and returns an error. It has to be used along with a function.

In [3]:
np.random(7)

TypeError: 'module' object is not callable

Simple Random Data is a colllection of functions within the numpy.random package that generates various random outcomes of data or subsets that have an equal probability of being chosen (https://www.investopedia.com/terms/s/simple-random-sample.asp). The are 10 functions that can be used in conjunction with numpy.random in order to generate simple random data. These will be discussed in more detail below.

Numpy.random.rand(x) generates a random set of numbers between 0 and 1 but not including 1. In the example below 7 random numbers between 0 and 1 but not including 1 are generated. X represents the number of random numbers that will be generated by the function. As see below np.random.rand does not generate any data and a value must be inserted for the value of 'x' in order to generate a random number.

In [4]:
np.random.rand

<function RandomState.rand>

In [5]:
np.random.rand(7)

array([ 0.88653351,  0.71487454,  0.17981218,  0.2539781 ,  0.26474571,
        0.53906778,  0.96855837])

Below 20 random numbers between 0 and 1 not including 1 are produced. When using np.random.rand(x), X is equivalent to the amount of random numbers generated.

In [6]:
np.random.rand(20)

array([ 0.32704802,  0.19222496,  0.98408564,  0.45737391,  0.89130763,
        0.13147491,  0.66380615,  0.82398975,  0.41467384,  0.05027301,
        0.83873436,  0.47322913,  0.36409601,  0.11064986,  0.6029997 ,
        0.33785509,  0.03402904,  0.87306562,  0.40804218,  0.07585679])

Np.random.rand(a,b) generates a random selection of numbers between 0 and 1 not including 1, however (a) represents the number of rows and (b) represents the amount of random numbers in that row. Please see below where 3 rows with 4 numbers in each row are generated.

In [6]:
np.random.rand(3, 4)

array([[ 0.94634915,  0.05739633,  0.7632177 ,  0.77783606],
       [ 0.31012589,  0.36351215,  0.35428922,  0.11070302],
       [ 0.42042899,  0.60693288,  0.3635991 ,  0.37560407]])

In [11]:
np.random.randn(29)

array([-1.02294218, -1.60023477, -1.40038252, -0.65734725,  0.72432297,
       -0.03431326, -0.67232123, -1.40979017,  0.27685975, -1.2699134 ,
       -1.84292729, -1.39224816, -0.28712183,  1.18927846,  1.53942754,
       -0.10883723,  0.72306405, -1.20210357,  1.46813358,  0.92734871,
        1.39743197, -0.1871966 ,  0.00792302, -0.67560959, -1.05639753,
        1.20036609,  0.06034499,  0.79551963,  1.64950291])

In [9]:
np.random.normal(5)

6.105090282189843

Numpy.random is a tool used in python to generate a random selection of numbers or random datasets. There are various differentiations of numpy.random.

Numpy.random.rand generates a random set of numbers between 0 and 1 but not including 1.Numpy.random is a tool used in python to generate a random selection of numbers or random datasets. Please see example below:


In [ ]:
numpy.random.rand(2)

In [8]:
np.random.normal(55)

54.879331866531096

In [7]:
np.random.normal

<function RandomState.normal>

In [15]:
np.random.normal(14)

15.897931699520822

In [12]:
#np.rand.rand(x) generates an array of x amount of numbers between 0 and 1 but not including 1. nupy
#In the examples below an array of 6 and 25 random numbers are created.
np.random.rand(6)


array([ 0.28585378,  0.06555019,  0.48148501,  0.97964273,  0.03200957,
        0.30440784])

In [13]:
np.random.rand(25)

array([ 0.59235392,  0.64948817,  0.31929259,  0.97095249,  0.59901688,
        0.13240716,  0.02440977,  0.07336042,  0.39259937,  0.81463549,
        0.82269928,  0.04522743,  0.41226354,  0.88256934,  0.82765764,
        0.45059467,  0.09357349,  0.62689294,  0.93477768,  0.65780961,
        0.71222106,  0.36970427,  0.7925234 ,  0.88421789,  0.86186634])

In [11]:
np.random.choice(522)

238

In [14]:
np.random.random(2)

array([ 0.96479596,  0.5344789 ])

In [15]:
np.random.randn(1)

array([ 1.79439602])

In [16]:
np.random.randn(45)

array([ 0.550734  , -0.18034681,  0.80284627, -1.24284468,  1.63733878,
       -0.68293737,  0.38127806,  1.0571557 ,  0.94770794, -0.05081263,
       -0.38903497,  0.884108  ,  0.87866014,  0.40176155, -1.71374184,
        1.22984641,  0.71580236, -0.11965335,  0.60906513,  1.03034347,
        1.43499204,  1.63523153, -0.06334411,  0.43603724, -0.62634484,
       -0.60532002, -1.10576321, -0.1146511 ,  0.21301772,  0.68223705,
       -0.54963561,  0.7841084 ,  1.05713897, -0.61716735, -1.53127262,
       -0.15254565,  0.26689651, -1.10792242,  1.0203468 , -0.78500111,
        0.29479748, -0.13312054, -0.60257886,  0.57643977, -0.02167002])

Np.random.bytes(x) returns random bytes. The higher the value of x the longer the random bytes printed out. Please see exmples below where x is 3 and a small random byte is printed, while when x is 56 a much longer output is produced.

In [17]:
np.random.bytes(3)

b'\x95\xcax'

In [18]:
np.random.bytes(12)

b'i\xdao\x97VZ\xdc\x1e\xde\x1dkF'

In [20]:
np.random.bytes

<function RandomState.bytes>

In [23]:
np.random.bytes(56)

b'~\xbb1\xfa\xcc\x8cM\xe4\xcf\xdb\xd3\xc9V7\xb1m\xe3e\x01\x93\x1eZ\xe7\x97\xb5\xc6e\n\x9c;\xa4|\xe8\x01@\x8a\xf4\xba-\xa3\x1d\x0e\xac\xf9bcb\x05\xfa\xf4\xd1\x12\xe4\x87>\x8f'